#!/bin/bash
#--------------------------------------------------------------
# This script runs terraform command and create main_init.tf file.
# main_init.tf generates terraform backend block and provider(azurerm/azuread).
# 
# if you want to run this script, need to add this following environment.
# - ENV
# - BUCKET
# - GOOGLE_CLOUD_KEYFILE_JSON
# - PROJECT_ID
# - REGION
# - ZONE
# - IS_GENERATE_PROVIDER
# 
# usage
# ex) tf plan
# ex) tf apply
#--------------------------------------------------------------
set -e

# name
NAME=`basename $0`
# script directory
SCRIPT_DIR=$(cd $(dirname $0); pwd)
# arguments
COMMAND=$@

# terraform-state prefix
if [ -e "terraform-state.prefix" ]; then
  PREFIX=`cat terraform-state.prefix | sed -e "s/[\r\n]\+//g"`
else
  PREFIX=terraform.tfstate
fi

# usage function
function usage () {
  echo "terraform needs $1 environment parameter."
  echo "usage: ${NAME} {command...}" 1>&2
  exit 1
}

# if [ $COMMAND = "destroy" ]; then
#   echo "terraform destroies command can't access now."
#   exit 1
# fi

# check environment
if [ -z $ENV ]; then
  usage ENV
  exit 1
fi
if [ -z $BUCKET ]; then
  usage BUCKET
  exit 1
fi
if [ -z $GOOGLE_CLOUD_KEYFILE_JSON ]; then
  usage GOOGLE_CLOUD_KEYFILE_JSON
  exit 1
fi
if [ -z $PROJECT_ID ]; then
  usage PROJECT_ID
  exit 1
fi
if [ -z $REGION ]; then
  usage ZONE
  exit 1
fi
if [ -z $ZONE ]; then
  usage ZONE
  exit 1
fi
if [ -z $IS_GENERATE_PROVIDER ]; then
  usage IS_GENERATE_PROVIDER
  exit 1
fi

# export TF_LOG=1
# export TF_LOG_PATH='./terraform.log'
rm -f terraform.log crash.log main_init.tf
if [ $IS_GENERATE_PROVIDER -eq "1" ]; then
  cat $SCRIPT_DIR/files/main.template.tf | sed -e "s/##BUCKET##/${BUCKET}/g" > ./main_init.tf
  cat ./main_init.tf | sed -i -e "s@##PREFIX##@${PREFIX}@g" ./main_init.tf
  cat ./main_init.tf | sed -i -e "s@##GOOGLE_CLOUD_KEYFILE_JSON##@${GOOGLE_CLOUD_KEYFILE_JSON}@g" ./main_init.tf
  cat ./main_init.tf | sed -i -e "s/##PROJECT_ID##/${PROJECT_ID}/g" ./main_init.tf
  cat ./main_init.tf | sed -i -e "s/##REGION##/${REGION}/g" ./main_init.tf
  cat ./main_init.tf | sed -i -e "s/##ZONE##/${ZONE}/g" ./main_init.tf
fi
terraform init
terraform $COMMAND -var-file=terraform.$ENV.tfvars 
