#!/bin/bash
#--------------------------------------------------------------
# Docker CMD for AWS
# This script uses this gcp environment, please check it.
# https://github.com/y-miyazaki/vscode-remote-development-terraform-aws
#--------------------------------------------------------------
set -e

# set aws default profile.
if [ -n "${AWS_ACCESS_KEY_ID}" ] && [ -n "${AWS_SECRET_ACCESS_KEY}" ] && [ -n "${AWS_DEFAULT_REGION}" ]; then
    aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}" --profile default
    aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" --profile default
    aws configure set region "${AWS_DEFAULT_REGION}" --profile default
fi

# keep container.
tail -f /dev/null
