#!/bin/bash
#--------------------------------------------------------------
# Docker CMD for AWS
# This script uses this gcp environment
#--------------------------------------------------------------
set -e

# Set aws default profile.
if [ -n "${AWS_ACCESS_KEY_ID}" ] && [ -n "${AWS_SECRET_ACCESS_KEY}" ] && [ -n "${AWS_DEFAULT_REGION}" ]; then
    aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}" --profile default
    aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" --profile default
    aws configure set region "${AWS_DEFAULT_REGION}" --profile default
fi

# Create terraform plugin dirctory.
if [ -n "${TF_PLUGIN_CACHE_DIR}" ]; then
    mkdir -p "${TF_PLUGIN_CACHE_DIR}"
fi

# keep container.
tail -f /dev/null
