#!/bin/bash
#--------------------------------------------------------------
# Docker CMD for Azure
# This script uses this azure environment.
#--------------------------------------------------------------
set -e
# Set az login
if [ -n "${ARM_CLIENT_ID}" ] && [ -n "${ARM_CLIENT_SECRET}" ] && [ -n "${ARM_TENANT_ID}" ]; then
    az login --service-principal --username "${ARM_CLIENT_ID}" --password "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
fi

# Create terraform plugin dirctory.
if [ -n "${TF_PLUGIN_CACHE_DIR}" ]; then
    mkdir -p "${TF_PLUGIN_CACHE_DIR}"
fi

# keep container.
tail -f /dev/null
