#!/bin/bash
#--------------------------------------------------------------
# Docker CMD for Azure
# This script uses this azure environment, please check it.
# https://github.com/y-miyazaki/vscode-remote-development-terraform-azure
#--------------------------------------------------------------
set -e
# az login
if [ ! -z ${ARM_CLIENT_ID} ] && [ ! -z ${ARM_CLIENT_SECRET} ] && [ ! -z ${ARM_TENANT_ID} ]; then
    az login --service-principal --username ${ARM_CLIENT_ID} --password ${ARM_CLIENT_SECRET} --tenant ${ARM_TENANT_ID}
fi

# keep container.
tail -f /dev/null
