#!/bin/bash
# ------------------------------------------------------------------------
# Create Service Principal
# 
# You need to check this following URL.
# https://docs.microsoft.com/ja-jp/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest
# ------------------------------------------------------------------------
set -e
NAME=`basename $0`

# usage function
function usage () {
    cat <<EOF
$(basename ${0}) is a tool for create azure service principal

Usage:
    $(basename ${0}) -n {service principal name} [<options>]

Options:
    -g           Authrize Azure Active Directory Graph
    -i           The Client ID
    -n {value}   Service principal name
    -h           Usage $(basename ${0})
EOF
exit 1
}

while getopts ghi:n: opt
do
  case $opt in
    g ) AZURE_ACTIVE_DIRECTORY_GRAPH=1 ;;
    i ) ARM_CLIENT_ID=$OPTARG ;;
    n ) SERVICE_PRINCIPAL_NAME=$OPTARG ;;
    h ) usage ;;
    \? ) usage ;;
  esac
done

if [ -z $SERVICE_PRINCIPAL_NAME ]; then
    usage
fi

az login
az ad sp create-for-rbac -n "${SERVICE_PRINCIPAL_NAME}" --role contributor
az account show --query "{subscriptionId:id, tenantId:tenantId}"

if [ $AZURE_ACTIVE_DIRECTORY_GRAPH -eq 1 ]; then
    if [ -z $ARM_CLIENT_ID ]; then
        # Azure Active Directory Graph->Application.ReadWrite.All
        az ad app permission add --id $ARM_CLIENT_ID --api 00000002-0000-0000-c000-000000000000 --api-permissions 311a71cc-e848-46a1-bdf8-97ff7156d8e6=Role
        # Azure Active Directory Graph->Directroy.Read.All
        az ad app permission add --id $ARM_CLIENT_ID --api 00000002-0000-0000-c000-000000000000 --api-permissions 5778995a-e1bf-45b8-affa-663a9f3f4d04=Role
        # check permission
        az ad app permission list --id $ARM_CLIENT_ID
    fi
fi
