#!/bin/bash
#--------------------------------------------------------------
# Create my SSL Certification
# This command creates a self certificate.
# Create client certificate(crt) and server certificate (pfx / csr / pem).
#--------------------------------------------------------------
set -e

# variables
DIR=certs

# usage function
function usage () {
    echo "${1}"
    cat <<EOF

This command creates a self certificate.
Create client certificate(crt) and server certificate (pfx / csr / pem).

Usage:
    $(basename "${0}") -f {san file} [<options>]
    $(basename "${0}") -f ./san.txt
    $(basename "${0}") -f ./san.txt -o ./certs

Options:
    -f {san file}         Subject Alternative Name file path.
    -o {output directory} output self-signed certificate directory. (default:certs)
    -h                    Usage $(basename "${0}")
EOF
    exit 1
}

while getopts f:ho: opt
do
    case $opt in
        f ) SAN=$OPTARG ;;
        o ) DIR=$OPTARG ;;
        h ) usage ;;
        \? ) usage ;;
    esac
done

# check
if [ -z "${SAN}" ]; then
    usage
fi
# check openssl command
if [ -z "$(command -v openssl)" ]; then
    usage "This command need to \"openssl\"."
fi

# make directory
mkdir -p "${DIR}"

# pass secret key.
openssl genrsa -out "${DIR}"/pk.pem -aes256 2048

# no pass secret key.
openssl rsa -in "${DIR}"/pk.pem -out "${DIR}"/pk_nopass.pem

# create csr
openssl req -new -key "${DIR}"/pk_nopass.pem -out "${DIR}"/server.csr

# display text
echo "--------------------------------------------------------------"
echo "Information"
echo "--------------------------------------------------------------"
openssl req -text -in "${DIR}"/server.csr
echo "--------------------------------------------------------------"

# create crt(need to SAN)
openssl x509 -req -days 365 -in "${DIR}"/server.csr -signkey "${DIR}"/pk_nopass.pem -out "${DIR}"/server.crt -extfile "${SAN}"

# create pfx
openssl pkcs12 -export -inkey "${DIR}"/pk_nopass.pem -in "${DIR}"/server.crt -out "${DIR}"/server.pfx
