#!/bin/bash
#--------------------------------------------------------------
# Docker CMD for GCP
# This script uses this gcp environment, please check it.
# https://github.com/y-miyazaki/vscode-remote-development-terraform-gcp
#--------------------------------------------------------------
set -e

if [ -n ${GOOGLE_CLOUD_KEYFILE_JSON} ] && [ -n ${PROJECT_ID} ]; then
    # gcloud authentication and install kubectl.
    /root/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${GOOGLE_CLOUD_KEYFILE_JSON}
    /root/google-cloud-sdk/bin/gcloud config set core/project ${PROJECT_ID}
fi

# keep container.
tail -f /dev/null
