#!/bin/bash
#------------------------------------------------------------------------
# Create Service Account
# see document
# https://cloud.google.com/iam/docs/creating-managing-service-accounts?hl=ja#iam-service-accounts-create-gcloud
#------------------------------------------------------------------------
set -e

NAME=`basename $0`

# usage function
function usage () {
    echo "usage: ${NAME} {project} {service account name} {service account display name} {service account description}" 1>&2
    exit 1
}

# service account name
PROJECT_ID=$1
# service account description
SA_NAME=${2:-terraform}
# service account display name
SA_DISPLAY_NAME=${3:-terraform}
# service account description
SA_DESCRIPTION=${4:-Service account used by terraform}


if [ -z $PROJECT_ID ]; then
    usage
fi

# login gcloud
gcloud auth login

# create service account
set +e
gcloud beta iam service-accounts create $SA_NAME \
--project $PROJECT_ID \
--description "$SA_DESCRIPTION" \
--display-name "$SA_DISPLAY_NAME"
set -e

# set iam role editor
gcloud projects add-iam-policy-binding $PROJECT_ID \
--member serviceAccount:${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com \
--role roles/owner

# service account list
gcloud iam service-accounts list --project $PROJECT_ID

# create key json file.
gcloud iam service-accounts keys create ${SA_NAME}-${PROJECT_ID}-key.json \
--iam-account ${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com