#!/bin/bash
#--------------------------------------------------------------
# This script runs terraform command and create main_init.tf file.
# main_init.tf generates terraform backend block and provider(google/googlebeta).
#
# if you want to run this script, need to add this following environment.
# - ENV
# - BUCKET
# - GOOGLE_CLOUD_KEYFILE_JSON
# - PROJECT_ID
# - REGION
# - ZONE
# - IS_GENERATE_PROVIDER
#--------------------------------------------------------------
set -e

#------------------------------------------------------------------------
# variables
#------------------------------------------------------------------------
# script directory
SCRIPT_DIR=$(cd "$(dirname "${0}")"; pwd)
# provider.json
PROVIDER_FILE=
BASE_PROVIDER_FILE="${SCRIPT_DIR}"/files/gcp/provider.json
USER_PROVIDER_FILE=provider.json

# usage function
function usage () {
    RED='\033[0;31m'
    NC='\033[0m' # No Color
    if [ -n "${1}" ]; then
        printf "%b%s%b\n" "${RED}" "${1}" "${NC}"
    fi
    cat <<EOF

This script runs terraform command and create main_init.tf file.
main_init.tf generates terraform backend block and provider(google/google-beta).

Usage:
    $(basename "${0}") {commands} [<options>]
    $(basename "${0}") plan
    $(basename "${0}") apply

Options:
    same terraform command options
EOF
    exit 1
}

# check jq command
if [ -z "$(command -v jq)" ]; then
    usage "This command need to install \"jq\"."
fi
# check terraform command
if [ -z "$(command -v terraform)" ]; then
    usage "This command need to install \"terraform\"."
fi

# arguments
COMMAND=$*
if [ $# -eq 0 ]; then
    usage
fi

# get provider.json
if [ -e "${USER_PROVIDER_FILE}" ]; then
    PROVIDER_FILE="${USER_PROVIDER_FILE}"
elif [ -e "${BASE_PROVIDER_FILE}" ]; then
    PROVIDER_FILE="${BASE_PROVIDER_FILE}"
else
    echo "can't find provider.json..."
    exit 1
fi
REQUIRED_VERSION=$(cat "${PROVIDER_FILE}" | jq -r .terraform.required_version)
BACKEND_GCS_PREFIX=$(cat "${PROVIDER_FILE}" | jq -r .terraform.backend_gcs.prefix)
GOOGLE_VERSION=$(cat "${PROVIDER_FILE}" | jq -r .google.version)
GOOGLE_BETA_VERSION=$(cat "${PROVIDER_FILE}" | jq -r .google_beta.version)

# check environment
if [ -z "${ENV}" ]; then
    usage "This command need to set \"ENV\" environment parameter."
fi
if [ -z "${BUCKET}" ]; then
    usage "This command need to set \"BUCKET\" environment parameter."
fi
if [ -z "${GOOGLE_CLOUD_KEYFILE_JSON}" ]; then
    usage "This command need to set \"GOOGLE_CLOUD_KEYFILE_JSON\" environment parameter."
fi
if [ -z "${PROJECT_ID}" ]; then
    usage "This command need to set \"PROJECT_ID\" environment parameter."
fi
if [ -z "${REGION}" ]; then
    usage "This command need to set \"REGION\" environment parameter."
fi
if [ -z "${ZONE}" ]; then
    usage "This command need to set \"ZONE\" environment parameter."
fi
if [ -z "${IS_GENERATE_PROVIDER}" ]; then
    usage "This command need to set \"IS_GENERATE_PROVIDER\" environment parameter."
fi

# export TF_LOG=1
# export TF_LOG_PATH='./terraform.log'
rm -f terraform.log crash.log main_init.tf
if [ "${IS_GENERATE_PROVIDER}" -eq "1" ]; then
    cp -p "${SCRIPT_DIR}"/files/gcp/main.template.tf ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##REQUIRED_VERSION##@${REQUIRED_VERSION}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GOOGLE_CLOUD_KEYFILE_JSON##@${GOOGLE_CLOUD_KEYFILE_JSON}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GCS_BUCKET##@${BUCKET}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GCS_PREFIX##@${BACKEND_GCS_PREFIX}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s/##PROJECT_ID##/${PROJECT_ID}/g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s/##REGION##/${REGION}/g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s/##ZONE##/${ZONE}/g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GOOGLE_VERSION##@${GOOGLE_VERSION}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GOOGLE_BETA_VERSION##@${GOOGLE_BETA_VERSION}@g" ./main_init.tf
fi
terraform init
# shellcheck disable=SC2086
terraform ${COMMAND} -var-file=terraform."${ENV}".tfvars
