#!/bin/bash
#--------------------------------------------------------------
# This script runs terraform command and create main_init.tf file.
# main_init.tf generates terraform backend block and provider(github).
#
# if you want to run this script, need to add this following environment.
#- IS_GENERATE_PROVIDER
#- GITHUB_TOKEN
#- GITHUB_INDIVISUAL
#- GITHUB_ORGANIZATION
#--------------------------------------------------------------
set -e

#------------------------------------------------------------------------
# variables
#------------------------------------------------------------------------
# script directory
SCRIPT_DIR=$(cd "$(dirname "${0}")"; pwd)
# provider.json
PROVIDER_FILE=
BASE_PROVIDER_FILE="${SCRIPT_DIR}"/files/github/provider.json
USER_PROVIDER_FILE=provider.json

# usage function
function usage () {
    RED='\033[0;31m'
    NC='\033[0m' # No Color
    if [ -n "${1}" ]; then
        printf "%b%s%b\n" "${RED}" "${1}" "${NC}"
    fi
    cat <<EOF

This script runs terraform command and create main_init.tf file.
main_init.tf generates terraform backend block and provider(github).

Usage:
    $(basename "${0}") {commands} [<options>]
    $(basename "${0}") plan
    $(basename "${0}") apply

Options:
    same terraform command options
EOF
    exit 1
}

# check jq command
if [ -z "$(command -v jq)" ]; then
    usage "This command need to install \"jq\"."
fi
# check terraform command
if [ -z "$(command -v terraform)" ]; then
    usage "This command need to install \"terraform\"."
fi

# arguments
COMMAND=$*
if [ $# -eq 0 ]; then
    usage
fi

# get provider.json
if [ -e "${USER_PROVIDER_FILE}" ]; then
    PROVIDER_FILE="${USER_PROVIDER_FILE}"
elif [ -e "${BASE_PROVIDER_FILE}" ]; then
    PROVIDER_FILE="${BASE_PROVIDER_FILE}"
else
    echo "can't find provider.json..."
    exit 1
fi
REQUIRED_VERSION=$(cat "${PROVIDER_FILE}" | jq -r .terraform.required_version)

# check environment
if [ -z "${ENV}" ]; then
    usage "This command need to set \"ENV\" environment parameter."
fi
if [ -z "${GITHUB_TOKEN}" ]; then
    usage "This command need to set \"GITHUB_TOKEN\" environment parameter."
fi
if [ -z "${GITHUB_INDIVIDUAL}" ]; then
    usage "This command need to set \"GITHUB_INDIVIDUAL\" environment parameter."
fi
if [ "${GITHUB_INDIVIDUAL}" = "false" ] && [ -z "${GITHUB_ORGANIZATION}" ]; then
    usage "This command need to set \"GITHUB_ORGANIZATION\" environment parameter."
elif [ "${GITHUB_INDIVIDUAL}" = "true" ]; then
    GITHUB_ORGANIZATION=""
else
    GITHUB_ORGANIZATION="organization = \"${GITHUB_ORGANIZATION}\""
fi
# export TF_LOG=1
# export TF_LOG_PATH='./terraform.log'
rm -f terraform.log crash.log main_init.tf
if [ "${IS_GENERATE_PROVIDER}" -eq "1" ]; then
    cp -p "${SCRIPT_DIR}"/files/github/main.template.tf ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##REQUIRED_VERSION##@${REQUIRED_VERSION}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GITHUB_TOKEN##@${GITHUB_TOKEN}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GITHUB_INDIVIDUAL##@${GITHUB_INDIVIDUAL}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##GITHUB_ORGANIZATION##@${GITHUB_ORGANIZATION}@g" ./main_init.tf
fi
terraform init
# shellcheck disable=SC2086
terraform ${COMMAND} -var-file=terraform."${ENV}".tfvars
