#!/bin/bash
#--------------------------------------------------------------
# Docker CMD for Github
# This script uses this github environment.
#--------------------------------------------------------------
set -e

# keep container.
tail -f /dev/null
