#!/bin/bash
# ------------------------------------------------------------------------
# Docker CMD
# This shell is a script for CMD called in the following repository.
# 1. Keep the container.
# ------------------------------------------------------------------------

# keep container.
tail -f /dev/null
