#!/bin/bash
#------------------------------------------------------------------------
# Docker CMD
# This shell is a script for CMD called in the following repository.
# 1. Keep the container.
# 2. Automatically configure ssh for the private repository of a specific domain.
#------------------------------------------------------------------------
# SSH for private repository
if [ -n "${GIT_DOMAIN}" ]; then
    ssh-keyscan "${GIT_DOMAIN}" >> /root/.ssh/known_hosts && \
    echo -e "[url \"git@${GIT_DOMAIN}:\"]\n\tinsteadOf = https://${GIT_DOMAIN}/" >> /root/.gitconfig && \
    echo -e "Host ${GIT_DOMAIN}\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
fi

# keep container.
tail -f /dev/null
