#!/bin/bash
set -e
#--------------------------------------------------------------
# scan open port
#--------------------------------------------------------------
#--------------------------------------------------------------
# variables
#--------------------------------------------------------------
EXIT_FLG=0

# usage function
function usage () {
    RED='\033[0;31m'
    NC='\033[0m' # No Color
    if [ -n "${1}" ]; then
        printf "%b%s%b\n" "${RED}" "${1}" "${NC}"
    fi
    cat <<EOF

This script will check the specified Host and return an error if the port is open.
It is used to check if the port of a specific host is accessible or not.

Usage:
    $(basename "${0}") {commands} {options}
    $(basename "${0}") -f host.txt
    $(basename "${0}") -s 127.0.0.1

Options:
    -f {host list file}        Specify the IP address or host name of the port scan target.
    -s {host}                 Specify the IP address or host name of the port scan target.
    -h                        Usage $(basename "${0}")
Example file:
---
127.0.0.1
ec2-xxx-xxx-xxx-xxx.ap-northeast-1.compute.amazonaws.com
---
EOF
    exit 1
}
while getopts f:h:s: opt
do
    case $opt in
        f ) FILE=$OPTARG ;;
        h ) usage ;;
        s ) HOST=$OPTARG ;;
        \? ) usage ;;
    esac
done

# check aws command
if [ -z "$(command -v nmap)" ]; then
    usage "This command need to install \"nmap\"."
fi

if [ -n "${FILE}" ]; then
    if [ ! -e "${FILE}" ]; then
        usage "${FILE} does not exists."
    fi
    while read -r line
    do
        RETURN=$(nmap -Pn ${line})
        CHECK=$(echo "${RETURN}" | grep "open")
        if [ -n "${CHECK}" ]; then
            echo "--------------------------------"
            echo "${RETURN}"
            echo "--------------------------------"
            EXIT_FLG=1
        fi
    done < "${FILE}"
else
    if [ -z "${HOST}" ]; then
        usage "-s option is not specified."
    fi
    RETURN=$(nmap -Pn ${HOST})
    CHECK=$(echo "${RETURN}" | grep "open")
    if [ -n "${CHECK}" ]; then
        echo "--------------------------------"
        echo "${RETURN}"
        echo "--------------------------------"
        EXIT_FLG=1
    fi
fi
exit ${EXIT_FLG}
